global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Alertmanager configuration
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "mytodoapp"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["backend:8000"]
    # Enable HTTP basic auth if your metrics endpoint requires it
    # basic_auth:
    #   username: admin
    #   password: password

# Rule files to evaluate alerts
rule_files:
  - "/etc/prometheus/rules/*.yml"